// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_QOQu2A_mD8Va8mLm9Y74iC4QN13m554',
    appId: '1:708288160410:web:9252cc76ced64e702ff523',
    messagingSenderId: '708288160410',
    projectId: 'appactivity-99e1b',
    authDomain: 'appactivity-99e1b.firebaseapp.com',
    storageBucket: 'appactivity-99e1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEowQaDYZkCT5PpuFMLazNlKtYOICR5HU',
    appId: '1:708288160410:android:e07f4595c5fec0142ff523',
    messagingSenderId: '708288160410',
    projectId: 'appactivity-99e1b',
    storageBucket: 'appactivity-99e1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARJzwsFuF9hYIxAF8q4L-OIoEvN3YU8Mg',
    appId: '1:708288160410:ios:c142bbe93163eabc2ff523',
    messagingSenderId: '708288160410',
    projectId: 'appactivity-99e1b',
    storageBucket: 'appactivity-99e1b.appspot.com',
    iosBundleId: 'com.example.saadLaabiActivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARJzwsFuF9hYIxAF8q4L-OIoEvN3YU8Mg',
    appId: '1:708288160410:ios:c142bbe93163eabc2ff523',
    messagingSenderId: '708288160410',
    projectId: 'appactivity-99e1b',
    storageBucket: 'appactivity-99e1b.appspot.com',
    iosBundleId: 'com.example.saadLaabiActivity',
  );
}
